#!/bin/bash

# Script to display Cloudflare Pages configuration for copy-paste

echo "=========================================="
echo "CLOUDFLARE PAGES DASHBOARD CONFIGURATION"
echo "=========================================="
echo ""
echo "Go to: https://dash.cloudflare.com/ → Pages → Your Project → Settings → Builds & deployments"
echo ""
echo "Framework preset: Next.js"
echo ""
echo "Root directory: apps/web"
echo ""
echo "Build command:"
echo "cd ../.. && pnpm install && pnpm build:sdks && NODE_ENV=production pnpm --filter erc8004-web build"
echo ""
echo "Build output directory: .next"
echo ""
echo "Node.js version: 18"
echo ""
echo "=========================================="
echo "ENVIRONMENT VARIABLES"
echo "=========================================="
echo ""
echo "Go to: Settings → Environment variables → Add variable"
echo "Make sure 'Production' environment is selected for each."
echo ""
echo "NEXT_PUBLIC_WEB3AUTH_CLIENT_ID"
echo "Value: BLPEpiCGGemncsyRbSt1NucfuR4IxWiGVPpuz0-8xNtoRtBn_d_XZxkcwm8c9V_FQUAj_1q9WuJNm7NYLnBORgE"
echo ""
echo "NEXT_PUBLIC_ETH_SEPOLIA_CHAIN_ID_HEX"
echo "Value: 0xaa36a7"
echo ""
echo "NEXT_PUBLIC_ETH_SEPOLIA_RPC_URL"
echo "Value: https://eth-sepolia.g.alchemy.com/v2/WvEny4nR70VTUMX0DfR-A"
echo ""
echo "NEXT_PUBLIC_ETH_SEPOLIA_ENS_REGISTRY"
echo "Value: 0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"
echo ""
echo "NEXT_PUBLIC_ETH_SEPOLIA_ENS_RESOLVER"
echo "Value: 0xE99638b40E4Fff0129D56f03b55b6bbC4BBE49b5"
echo ""
echo "NEXT_PUBLIC_ETH_SEPOLIA_IDENTITY_REGISTRY"
echo "Value: 0x8004a6090Cd10A7288092483047B097295Fb8847"
echo ""
echo "GRAPHQL_API_URL"
echo "Value: https://erc8004-indexer-graphql.richardpedersen3.workers.dev/graphql"
echo ""
echo "=========================================="
echo "TESTING AFTER DEPLOYMENT"
echo "=========================================="
echo ""
echo "1. Visit: https://www.8004-agent.com"
echo "2. Test API: https://www.8004-agent.com/api/agents"
echo "   Should return JSON (not 500 error)"
echo "3. Check browser console for errors"
echo ""
echo "=========================================="

