"use strict";(()=>{var e={};e.id=961,e.ids=[961],e.modules={20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},1725:(e,t,a)=>{a.r(t),a.d(t,{originalPathname:()=>g,patchFetch:()=>N,requestAsyncStorage:()=>l,routeModule:()=>d,serverHooks:()=>m,staticGenerationAsyncStorage:()=>p});var n={};a.r(n),a.d(n,{GET:()=>u,dynamic:()=>c});var r=a(17370),i=a(35317),s=a(2579),o=a(26567);let c="force-dynamic";async function h(e,t={}){let a=process.env.GRAPHQL_API_URL||process.env.NEXT_PUBLIC_GRAPHQL_API_URL;try{if(!a)return console.warn("No GRAPHQL_URL configured"),null;let n=await fetch(a,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:e,variables:t})});if(!n.ok)return console.error(`GraphQL request failed: ${n.status} ${n.statusText}`),null;let r=await n.json();if(r.errors)return console.error("GraphQL errors:",r.errors),null;return r.data}catch(e){return console.error("GraphQL fetch error:",e?.message||e),null}}async function u(){try{let e=`
      query GetStats {
        agents(limit: 10000, offset: 0) {
          chainId
          agentId
          agentName
          description
          image
          metadataURI
          ensEndpoint
          createdAtTime
        }
      }
    `,t=await h(e);if(!t||!t.agents)return o.NextResponse.json({summary:{totalAgents:0,totalChains:0,chains:[]},metadata:{chains:[]},ens:{chains:[]},activity:{recent24h:[]},topAgents:[]});let a=t.agents||[],n=Math.floor(Date.now()/1e3)-86400,r={};a.forEach(e=>{r[e.chainId]||(r[e.chainId]=[]),r[e.chainId].push(e)});let i=e=>{switch(e){case 11155111:return"ETH Sepolia";case 84532:return"Base Sepolia";case 11155420:return"OP Sepolia";default:return`Chain ${e}`}},s=Object.keys(r).map(e=>{let t=parseInt(e),a=r[t],s=a.filter(e=>e.metadataURI).length,o=a.filter(e=>e.ensEndpoint).length,c=a.filter(e=>e.createdAtTime>n).length;return{chainId:t,chainName:i(t),count:a.length,withMetadata:s,withoutMetadata:a.length-s,withENS:o,withoutENS:a.length-o,recentCount:c}}),c=a.slice(0,10).map(e=>({chainId:e.chainId,chainName:i(e.chainId),agentId:e.agentId,agentName:e.agentName||"Unnamed",ensName:e.ensEndpoint||null}));return o.NextResponse.json({summary:{totalAgents:a.length,totalChains:s.length,chains:s.map(e=>({chainId:e.chainId,chainName:e.chainName,agentCount:e.count}))},metadata:{chains:s.map(e=>({chainId:e.chainId,chainName:e.chainName,withMetadata:e.withMetadata,withoutMetadata:e.withoutMetadata,metadataPercentage:e.count>0?Math.round(e.withMetadata/e.count*100):0}))},ens:{chains:s.map(e=>({chainId:e.chainId,chainName:e.chainName,withENS:e.withENS,withoutENS:e.withoutENS,ensPercentage:e.count>0?Math.round(e.withENS/e.count*100):0}))},activity:{recent24h:s.map(e=>({chainId:e.chainId,chainName:e.chainName,recentCount:e.recentCount}))},topAgents:c})}catch(e){return console.error("Stats API error:",e),o.NextResponse.json({summary:{totalAgents:0,totalChains:0,chains:[]},metadata:{chains:[]},ens:{chains:[]},activity:{recent24h:[]},topAgents:[]})}}let d=new r.AppRouteRouteModule({definition:{kind:i.x.APP_ROUTE,page:"/api/stats/route",pathname:"/api/stats",filename:"route",bundlePath:"app/api/stats/route"},resolvedPagePath:"/home/barb/erc8004/erc-8004-identity-indexer/apps/web/app/api/stats/route.ts",nextConfigOutput:"",userland:n}),{requestAsyncStorage:l,staticGenerationAsyncStorage:p,serverHooks:m}=d,g="/api/stats/route";function N(){return(0,s.patchFetch)({serverHooks:m,staticGenerationAsyncStorage:p})}}};var t=require("../../../webpack-runtime.js");t.C(e);var a=e=>t(t.s=e),n=t.X(0,[910,145],()=>a(1725));module.exports=n})();